import type { Metadata } from "next";
import { Fraunces, Manrope } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { CookieConsent } from "@/components/cookie-consent";
import { FIRM_PHONE, FIRM_EMAIL, FIRM_ADDRESS_LINES } from "@/lib/constants";

const SITE_URL = "https://www.catapultfr.com";
const OG_IMAGE = "/images/generated/e656b128-f2e0-427e-a4c2-07e58fa6812e.webp";

// Self-hosted via next/font/google instead of the external
// fonts.googleapis.com/fonts.gstatic.com <link>/@import used previously.
// This inlines the font-face CSS at build time and serves the woff2 files
// from our own domain, removing an external render-blocking stylesheet
// fetch (and the chained font-file requests behind it) from the critical
// rendering path. Weights/styles mirror the previous Google Fonts URL.
const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-fraunces",
});
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Catapult Fundraising | Capital Campaign and Donor Engagement Consultants",
    template: "%s | Catapult Fundraising",
  },
  description:
    "Catapult Fundraising guides nonprofits from feasibility study through public-phase calling, raising more from major donors, annual funds, and community campaigns. Based in Henderson, NV, serving clients nationwide.",
  keywords: [
    "capital campaign consultant",
    "nonprofit fundraising consultant",
    "donor calling program",
    "feasibility study nonprofit",
    "annual fund calling services",
    "mid-level donor engagement",
    "legacy and planned giving consultant",
    "Las Vegas fundraising consultant",
    "capital campaign counsel",
    "nonprofit consulting firm",
    "RNL",
    "Ruffalo Noel Levitz",
    "Telemarketing",
    "Phonathon",
    "The Phonathon",
    "Student Calling Program",
    "CCS Fundraising",
    "Grenzebach Glier",
    "Convergent Nonprofit Solutions",
    "M. Gale & Associates",
    "Beacon",
    "Gailerry",
    "Walsh & Associates",
    "Graham-Pelton",
    "Marts & Lundy",
    "Capital Campaign Pro",
    "DCM",
    "Telephone fundraising",
    "Major Gifts Consulting",
    "Capacity Building",
    "Mid Level Donor",
    "Veritus Group",
    "NextAfter",
    "Team Allegiance",
    "EAB",
    "Neon One",
    "We Are Moore",
    "Mission Wired",
    "Telefundraising",
    "Public Phase",
    "capital campaign consulting firm",
    "nonprofit capital campaign consultant",
    "capital campaign feasibility study",
    "capital campaign planning services",
    "capital campaign case for support",
    "capital campaign strategy consultant",
    "nonprofit fundraising consultant near me",
    "nonprofit phonathon services",
    "public phase calling campaign",
    "nonprofit calling campaign services",
    "alumni annual giving program",
    "donor participation rate consultant",
    "mid-level donor engagement program",
    "donor engagement officer program",
    "donor upgrade strategy",
    "major gift pipeline development",
    "donor cultivation consultant",
    "donor stewardship program",
    "capacity building fundraising",
    "board fundraising training",
    "major gift officer training",
    "donor segmentation strategy",
    "legacy giving consultant",
    "bequest program for nonprofits",
    "legacy call program",
    "deferred gift fundraising",
    "planned giving outreach services",
    "faith-based capital campaign consultant",
    "diocesan capital campaign consultant",
    "higher education capital campaign consultant",
    "hospital foundation fundraising consultant",
    "healthcare capital campaign consultant",
    "arts and culture fundraising consultant",
    "youth development fundraising consultant",
    "human services capital campaign",
    "Henderson NV nonprofit consultant",
    "Nevada capital campaign consultant",
    "New Jersey capital campaign consultant",
    "Texas nonprofit fundraising consultant",
    "Catapult Fundraising",
    "national capital campaign consultant",
    "nationwide nonprofit fundraising consultant",
    "national fundraising consulting firm",
    "moves management",
    "wealth screening",
    "donor pyramid",
    "gift table",
    "case for support",
    "silent phase capital campaign",
    "campaign readiness assessment",
    "campaign steering committee",
    "donor-advised fund",
    "charitable remainder trust",
    "charitable lead trust",
    "charitable gift annuity",
    "IRA charitable rollover",
    "qualified charitable distribution",
    "beneficiary designation gifts",
    "BWF",
    "Orr Group",
    "Alexander Haas",
    "Gail Perry Group",
    "Generis",
    "Donorly",
    "Blackbaud",
    "Bloomerang",
    "DonorPerfect",
    "Virtuous",
    "synagogue capital campaign",
    "Jewish federation campaign",
    "YMCA capital campaign",
    "library foundation capital campaign",
    "Scouting capital campaign",
    "performing arts center capital campaign",
    "capital campaign consultant cost",
    "capital campaign consultant fees",
    "hire a fundraising consultant",
    "capital campaign consultant RFP",
    "best capital campaign consultants",
    // --- Added from Catapult_Fundraising_SEO_AEO_Keyword_Master_List ---
    "fundraising consultant",
    "fundraising consulting firms",
    "nonprofit fundraising consulting",
    "fundraising strategy consultant",
    "nonprofit fundraising strategy",
    "fundraising consulting services",
    "best fundraising consultants",
    "nonprofit consultant",
    "nonprofit consulting firms",
    "nonprofit consulting services",
    "fundraising advisor",
    "nonprofit fundraising advisor",
    "fundraising expert",
    "fundraising strategic planning",
    "nonprofit development strategy",
    "nonprofit development consultant",
    "fundraising plan for nonprofits",
    "nonprofit fundraising plan",
    "fundraising strategy",
    "fundraising best practices",
    "fundraising planning",
    "comprehensive fundraising strategy",
    "fundraising program assessment",
    "nonprofit revenue strategy",
    "capital campaign consulting",
    "capital campaign consultants",
    "capital campaign consulting firms",
    "capital campaign planning",
    "capital campaign strategy",
    "capital campaign feasibility study consultant",
    "capital campaign management",
    "capital campaign fundraising",
    "capital campaign firm",
    "capital campaign company",
    "capital campaign advisor",
    "capital campaign specialist",
    "capital campaign services",
    "nonprofit capital campaigns",
    "how to conduct a capital campaign",
    "how to start a capital campaign",
    "how to plan a capital campaign",
    "how much can a capital campaign raise",
    "capital campaign goal setting",
    "capital campaign timeline",
    "capital campaign phases",
    "capital campaign committee",
    "capital campaign leadership gifts",
    "capital campaign gift chart",
    "capital campaign case statement",
    "capital campaign best practices",
    "What is a capital campaign?",
    "How do you conduct a capital campaign?",
    "How do you plan a capital campaign?",
    "Does my nonprofit need a capital campaign?",
    "How do I know if my nonprofit is ready for a capital campaign?",
    "How much should a nonprofit raise in a capital campaign?",
    "How do you determine a capital campaign goal?",
    "How long does a capital campaign take?",
    "How much does a capital campaign consultant cost?",
    "What does a capital campaign consultant do?",
    "What is a capital campaign feasibility study?",
    "How much does a feasibility study cost?",
    "Who should conduct a capital campaign feasibility study?",
    "What percentage of a capital campaign should come from major gifts?",
    "How many gifts should make up a capital campaign?",
    "How do you create a capital campaign gift chart?",
    "What is the quiet phase of a capital campaign?",
    "When should a nonprofit announce a capital campaign?",
    "How do you recruit a capital campaign committee?",
    "What are the biggest capital campaign mistakes?",
    "major gifts consultant",
    "major gift consultant",
    "major gifts fundraising",
    "major gifts strategy",
    "major donor strategy",
    "major donor fundraising",
    "major gifts program",
    "major gift fundraising consultant",
    "major donor consultant",
    "major gift program consultant",
    "major donor identification",
    "major donor prospect research",
    "major donor cultivation",
    "major donor solicitation",
    "major gift solicitation",
    "major gift pipeline",
    "major gift portfolio management",
    "major gift officer strategy",
    "major gift fundraising plan",
    "how to find major donors",
    "how to identify major gift prospects",
    "how to cultivate major donors",
    "how to ask for a major gift",
    "how to build a major gifts program",
    "donor acquisition strategy",
    "nonprofit donor acquisition",
    "donor retention strategy",
    "nonprofit donor retention",
    "lapsed donor reactivation",
    "lapsed donor fundraising",
    "donor acquisition consultant",
    "donor retention consultant",
    "donor reactivation strategy",
    "nonprofit donor engagement",
    "donor engagement strategy",
    "donor stewardship strategy",
    "donor cultivation strategy",
    "donor lifecycle strategy",
    "increase donor retention",
    "increase average gift size",
    "increase nonprofit donor revenue",
    "why donors stop giving",
    "how to reactivate lapsed donors",
    "annual fund consultant",
    "annual giving consultant",
    "annual fund strategy",
    "annual giving strategy",
    "annual fund campaign",
    "annual giving program",
    "nonprofit annual fund",
    "annual fund fundraising",
    "annual fund strategy consultant",
    "annual giving campaign",
    "annual fund best practices",
    "annual giving best practices",
    "how to increase annual giving",
    "how to build an annual fund",
    "annual fund planning",
    "planned giving consultant",
    "planned giving consulting",
    "planned giving strategy",
    "planned giving program",
    "planned giving fundraising",
    "planned giving consultant nonprofit",
    "planned giving program consultant",
    "legacy giving program",
    "nonprofit planned giving",
    "planned giving marketing",
    "how to start a planned giving program",
    "how to increase planned gifts",
    "how to identify planned giving prospects",
    "planned giving best practices",
    "fundraising feasibility study",
    "feasibility study consultant",
    "nonprofit feasibility study",
    "capital campaign feasibility consultant",
    "feasibility study fundraising",
    "campaign feasibility study",
    "feasibility study cost",
    "nonprofit campaign feasibility study",
    "how does a fundraising feasibility study work",
    "fundraising event consultant",
    "nonprofit fundraising events",
    "fundraising event strategy",
    "nonprofit event fundraising",
    "fundraising event ideas",
    "corporate sponsorship consultant",
    "corporate sponsorship strategy",
    "nonprofit sponsorship strategy",
    "event sponsorship fundraising",
    "how to increase fundraising event revenue",
    "nonprofit board fundraising",
    "nonprofit board fundraising training",
    "board member fundraising",
    "board fundraising responsibilities",
    "how to get board members involved in fundraising",
    "nonprofit board development",
    "CEO fundraising training",
    "board member donor solicitation",
    "how to motivate nonprofit boards to fundraise",
    "fundraising gift chart",
    "fundraising gift pyramid",
    "capital campaign gift pyramid",
    "gift chart calculator",
    "capital campaign gift chart calculator",
    "fundraising goal calculator",
    "capital campaign goal calculator",
    "fundraising ROI",
    "nonprofit fundraising metrics",
    "AI for nonprofit fundraising",
    "AI fundraising",
    "AI donor research",
    "AI for nonprofits",
    "AI major donor prospecting",
    "AI donor prospect research",
    "AI fundraising strategy",
    "AI nonprofit fundraising tools",
    "how to use AI for fundraising",
    "ChatGPT for nonprofit fundraising",
  ],
  authors: [{ name: "Catapult Fundraising" }],
  creator: "Catapult Fundraising",
  publisher: "Catapult Fundraising",
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Catapult Fundraising",
    title: "Catapult Fundraising | Capital Campaign and Donor Engagement Consultants",
    description:
      "Full-service capital campaign counsel, annual fund calling, mid-level donor engagement, and legacy giving, all from one accountable nonprofit fundraising partner.",
    images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: "Catapult Fundraising" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Catapult Fundraising | Capital Campaign and Donor Engagement Consultants",
    description:
      "Full-service capital campaign counsel, annual fund calling, mid-level donor engagement, and legacy giving, all from one accountable nonprofit fundraising partner.",
    images: [OG_IMAGE],
  },
  category: "business",
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  "@id": `${SITE_URL}/#organization`,
  name: "Catapult Fundraising",
  alternateName: "Catapult Fundraising Consulting",
  url: SITE_URL,
  logo: "/images/generated/42ba78de-233b-4e8c-9f6c-bbdd4f9ab4ff.webp",
  image: OG_IMAGE,
  description:
    "Catapult Fundraising is a full-service fundraising consulting firm guiding nonprofits from feasibility study through public-phase calling, specializing in capital campaigns, annual fund calling, mid-level donor engagement, and legacy and planned giving.",
  telephone: FIRM_PHONE,
  email: FIRM_EMAIL,
  // Confirms to search engines that the LinkedIn and Facebook profiles are
  // this same entity. (Google Business Profile URL intentionally omitted --
  // add it here once the exact profile URL is confirmed.)
  sameAs: [
    "https://www.linkedin.com/company/catapult-fundraising",
    "https://www.facebook.com/catapultfr/",
  ],
  address: {
    "@type": "PostalAddress",
    streetAddress: `${FIRM_ADDRESS_LINES[0]}, ${FIRM_ADDRESS_LINES[1]}`,
    addressLocality: "Henderson",
    addressRegion: "NV",
    postalCode: "89014",
    addressCountry: "US",
  },
  areaServed: {
    "@type": "Country",
    name: "United States",
  },
  additionalLocations: [
    { "@type": "Place", address: { "@type": "PostalAddress", addressRegion: "NJ", addressCountry: "US" } },
    { "@type": "Place", address: { "@type": "PostalAddress", addressRegion: "TX", addressCountry: "US" } },
  ],
  priceRange: "$$$",
  // Client testimonials stay visible on the homepage
  // (components/testimonial-strip.tsx) -- they're just no longer inside
  // this Organization node's structured data. Google's structured data
  // guidelines don't allow a business to mark up reviews of itself; a
  // self-published review array on your own Organization/ProfessionalService
  // schema is exactly the pattern their policy prohibits, independent of
  // whether an aggregateRating is also present.
  hasOfferCatalog: {
    "@type": "OfferCatalog",
    name: "Fundraising Consulting Services",
    itemListElement: [
      {
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: "Capital Campaign Counsel",
          url: `${SITE_URL}/services/capital-campaign`,
          description:
            "Feasibility studies, campaign planning, quiet-phase major gift strategy, and public-phase calling for nonprofit capital campaigns.",
        },
      },
      {
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: "Legacy & Planned Giving",
          url: `${SITE_URL}/services/legacy-giving`,
          description:
            "Legacy Call identifies and closes bequests, beneficiary designations, and other deferred gifts from loyal, long-tenured donors.",
        },
      },
      {
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: "Mid-Level Donor Engagement",
          url: `${SITE_URL}/services/donor-engagement`,
          description:
            "An 8-stage, relationship-first program that upgrades mid-level donors and builds a qualified major gift pipeline.",
        },
      },
      {
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: "Annual Fund Calling",
          url: `${SITE_URL}/services/annual-fund`,
          description:
            "Trained Engagement Officers deliver segmented outreach, personalized asks, and digital stewardship for annual fund programs.",
        },
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${fraunces.variable} ${manrope.variable}`}>
      <body className="bg-[rgb(var(--paper))] text-[rgb(var(--ink))] antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {/* Apollo.io website visitor tracking. Deliberately a plain <script> tag
            (not next/script's <Script> component) so it is server-rendered as a
            literal <script> element in the initial HTML response -- Apollo's own
            install-verification check fetches raw HTML and looks for the literal
            tag, and next/script's client-hydration-only injection was invisible
            to that check even though it still ran fine in real browsers. */}
        <script
          id="apollo-tracker"
          dangerouslySetInnerHTML={{
            __html: `function initApollo(){var n=Math.random().toString(36).substring(7),o=document.createElement("script");
o.src="https://assets.apollo.io/micro/website-tracker/tracker.iife.js?nocache="+n,o.async=!0,o.defer=!0,
o.onload=function(){window.trackingFunctions.onLoad({appId:"6a7b2ca6343a240014fd522e"})},
document.head.appendChild(o)}initApollo();`,
          }}
        />
        <SiteHeader />
        <main>{children}</main>
        <SiteFooter />
        <CookieConsent />
      </body>
    </html>
  );
}
