import type { JagDashboardData } from "@/lib/jag-data";

// Anonymized sample of a live Catapult feasibility study dashboard, shown to
// prospects from the Capital Campaign deck page at /decks/sample-dashboard.
// The counts, dates, percentages, and interview quotes come from a real
// completed study; the organization name, contact names, and employers are
// fictional so nothing identifies the client or the people interviewed.
export const SAMPLE_ORG_NAME = "Bridgeway Youth Alliance";

export const SAMPLE_STUDY_DATA: JagDashboardData = {
  reportDate: "August 5, 2026",
  updatedAt: "2026-08-05T00:00:00.000Z",
  surveyRespondentCount: 26,
  stats: {
    totalProspects: 268,
    tier1: 56,
    tier2: 54,
    tier3: 52,
    tier4: 52,
    tier5: 54,
    dials: 1982,
    emailsSent: 283,
    completed: 27,
    scheduled: 1,
    toBeRescheduled: 5,
    declined: 24,
    deceased: 1,
    inCallingProcess: 210,
  },
  previousStats: {
    totalProspects: 268,
    completed: 22,
    scheduled: 5,
    toBeRescheduled: 6,
    declined: 18,
    deceased: 1,
    inCallingProcess: 216,
    dials: 1250,
    emailsSent: 282,
  },
  completedInterviews: [
    { name: "Owen Chandra", org: "Summit Insurance Group", date: "6/15/2026" },
    { name: "Rashad Moore", org: "", date: "6/17/2026" },
    { name: "Devon Patel", org: "", date: "6/18/2026" },
    { name: "Marisol Marchetti", org: "Statewide Workforce Board", date: "6/23/2026" },
    { name: "Colin Redmond", org: "Ironwood Capital", date: "6/24/2026" },
    { name: "Nadia Ito", org: "Prairie Mutual", date: "6/24/2026" },
    { name: "Gregory Ridgely", org: "", date: "6/26/2026" },
    { name: "Lila Alvarez", org: "Beacon Wealth Advisors", date: "6/30/2026" },
    { name: "Sanjay Radcliffe", org: "Grandview Public Schools", date: "6/30/2026" },
    { name: "Frances Kingsley", org: "Civic Trust of Harborview", date: "6/30/2026" },
    { name: "Bennett Delacroix", org: "Vantage Marketing Group", date: "7/6/2026" },
    { name: "Yvonne Solis", org: "", date: "7/8/2026" },
    { name: "Curtis Larkspur", org: "Office of Economic Development", date: "7/8/2026" },
    { name: "Adele Quintero", org: "Sterling Ridge Bank", date: "7/13/2026" },
    { name: "Hugo Whitaker", org: "", date: "7/14/2026" },
    { name: "Simone Beaumont", org: "Harborview Chamber of Commerce", date: "7/14/2026" },
    { name: "Trevor Sandoval", org: "Lakeside Health Partners", date: "7/14/2026" },
    { name: "Naomi Ferro", org: "", date: "7/15/2026" },
    { name: "Emmett Ambrose", org: "Northgate Credit Union", date: "7/17/2026" },
    { name: "Cleo Kerrigan", org: "", date: "7/20/2026" },
    { name: "Roland Sable", org: "Summit Insurance Group", date: "7/20/2026" },
    { name: "Vera Lund", org: "Trailhead Consulting", date: "7/22/2026" },
    { name: "Otis Lindqvist", org: "Fairmont Properties", date: "7/23/2026" },
    { name: "Bianca Rahim", org: "Statewide Workforce Board", date: "7/28/2026" },
    { name: "Silas Nakamura", org: "Ironwood Capital", date: "7/30/2026" },
    { name: "Rhonda Winters", org: "Prairie Mutual", date: "8/3/2026" },
    { name: "Malik Osborne", org: "Copperline Logistics", date: "8/4/2026" },
  ],
  scheduledInterviews: [
    { name: "Colin Cardwell", org: "Statewide Workforce Board", date: "8/6/2026" },
  ],
  toBeRescheduled: [
    { name: "Devon Fairbanks", org: "" },
    { name: "Marisol Baptiste", org: "" },
    { name: "Nadia Solis", org: "Statewide Workforce Board" },
    { name: "Gregory Larkspur", org: "Ironwood Capital" },
    { name: "Lila Quintero", org: "Prairie Mutual" },
  ],
  declined: [
    { name: "Marisol Kingsley", org: "", reason: "Not Interested" },
    { name: "Colin Delacroix", org: "Fairmont Properties", reason: "Not Interested" },
    { name: "Gregory Halloway", org: "Statewide Workforce Board", reason: "Does not do study interviews" },
    { name: "Lila Northrup", org: "Ironwood Capital", reason: "Does not do study interviews" },
    { name: "Sanjay Escalante", org: "Prairie Mutual", reason: "Too Busy" },
    { name: "Sanjay Whitaker", org: "", reason: "No longer lives in Harborview" },
    { name: "Frances Beaumont", org: "", reason: "Too Busy" },
    { name: "Bennett Sandoval", org: "Grandview Public Schools", reason: "Does not do study interviews" },
    { name: "Bennett Ashworth", org: "Civic Trust of Harborview", reason: "Recommended another person in his office to do interview" },
    { name: "Yvonne Osei", org: "", reason: "Personal Issues" },
    { name: "Curtis Halloway", org: "Longleaf Manufacturing", reason: "Too Busy, but likes what the organization does" },
    { name: "Adele Northrup", org: "", reason: "Too Busy" },
    { name: "Hugo Escalante", org: "", reason: "Too Busy" },
    { name: "Simone Pearson", org: "", reason: "Not Interested" },
    { name: "Trevor Castellano", org: "Harborview Chamber of Commerce", reason: "Out of Country" },
    { name: "Naomi Duvall", org: "", reason: "Too Busy" },
    { name: "Emmett Blythe", org: "", reason: "Too Busy" },
    { name: "Cleo Tran", org: "", reason: "Too Busy" },
    { name: "Roland Ballinger", org: "", reason: "Not Interested" },
    { name: "Vera Boone", org: "Summit Insurance Group", reason: "Out of Town" },
    { name: "Otis Chandra", org: "Trailhead Consulting", reason: "Not Interested" },
    { name: "Bianca Moore", org: "", reason: "Not Interested" },
    { name: "Silas Patel", org: "", reason: "Is no longer interested in doing interview" },
    { name: "Rhonda Marchetti", org: "", reason: "Not Interested" },
  ],
  deceased: [
    { name: "Nadia Osei", reason: "Passed Away" },
  ],
  feasibilitySignals: [
    {
      stat: "85%",
      label: "Rate the organization's reputation \u201cVery Good\u201d or \u201cGood\u201d",
      detail: "14 Very Good, 8 Good, 4 Don't Know \u2014 out of 26 respondents",
    },
    {
      stat: "69%",
      label: "Would consider a financial gift to the campaign if asked",
      detail: "18 Yes, 6 No, 1 Maybe, 1 Don't Know",
    },
    {
      stat: "60%",
      label: "Of likely donors would consider a multi-year commitment",
      detail: "9 of 15 who answered the multi-year follow-up said Yes",
    },
    {
      stat: "73%",
      label: "Are willing to make introductions to others in their network",
      detail: "19 of 26 respondents said Yes",
    },
    {
      stat: "42%",
      label: "Would consider a campaign leadership role",
      detail: "11 Yes, another 6 said Maybe",
    },
  ],
  missionThemes: [
    { label: "Workforce development", pct: "73%" },
    { label: "Opportunity & access", pct: "69%" },
    { label: "Mentorship", pct: "54%" },
    { label: "Student success", pct: "50%" },
    { label: "Leadership training", pct: "31%" },
  ],
  quotes: [
    "I believe Bridgeway has a very good reputation among those who know about the organization and understand the work it does in the community.",
    "I believe Bridgeway has a very good reputation because it consistently delivers measurable results for students who are most at risk of not graduating.",
    "I feel Bridgeway is a wonderful organization, is well respected, and has a positive reputation.",
    "Bridgeway aligns closely with what motivates me because it prepares young people for successful careers while helping them overcome challenges that could prevent them from reaching their goals.",
    "Bridgeway aligns with my passion for public education, helping young people develop meaningful life skills, and creating opportunities for students who may otherwise struggle to find their path.",
    "It aligns completely. I feel a strong sense of ownership and can clearly see the direct impact and the return on investment it brings to youth.",
    "That alignment is one of the reasons I serve on the board. I believe in the organization's mission, leadership, and ability to produce results.",
    "Bridgeway is very valuable and needed in this region. I see the dropout rates improving and feel Bridgeway is doing a very good job.",
    "I have seen firsthand the instructors' enthusiasm and passion, and it is very inspirational.",
    "From what I've seen, Bridgeway gets really good results for those that need another outlet and need a chance.",
    "Bridgeway's focus on youth and its commitment to preparing students for quality employment strongly align with my values.",
    "Bridgeway aligns closely with our organization's priorities because it focuses on education and workforce development.",
  ],
};
